insert into song values (1, 'PUSSYKILLER', 'Хип-Хоп', 'Гори ясно');
insert into song values (2, 'PUSSYKILLER', 'Хип-Хоп', 'Поздно');
insert into song values (3, 'Markul', 'Хип-Хоп', 'Blues');
insert into song values (4, 'Markul', 'Хип-Хоп', 'Moulin rouge');
insert into song values (5, 'ХуйЗнает', 'Хип-Хоп', 'Гори ясно');
insert into song values (6, 'PUSSYKILLER', 'Хип-Хоп', 'Гори ясно');
insert into song values (7, 'DIMA ROUX', 'Хип-Хоп', '0 to 100');
insert into song values (8, 'PHARAOH', 'Хип-Хоп', 'Эми');
insert into song values (9, 'PHARAOH', 'Хип-Хоп', 'В ванне');
insert into playlist values (1,'Хип-хоп треки, выходившие в 2023 году','Хип-хоп 2023');
insert into playlist values (2,'Хип-хоп треки, выходившие в 2022 году','Хип-хоп 2022');
insert into playlist values (3,'Хип-хоп треки, выходившие в 2021 году','Хип-хоп 2021');
insert into playlist values (4,'Лучшие треки за 2022 год, РЗТ','Плейлист 2022 РЗТ');
insert into playlist values (5,'Лучшие треки за 2021 год, РЗТ','Плейлист 2021 РЗТ');
insert into playlist_songs values (1, 1, 1, 1);
insert into playlist_songs values (2, 2, 1, 2);
insert into playlist_songs values (3, 3, 1, 3);
insert into playlist_songs values (4, 4, 1, 4);
insert into playlist_songs values (5, 5, 1, 5);
insert into playlist_songs values (6, 1, 2, 1);
insert into playlist_songs values (7, 1, 3, 6);
insert into playlist_songs values (8, 2, 2, 7);
insert into playlist_songs values (9, 2, 3, 8);
insert into playlist_songs values (10, 1, 4, 9);